### ISSUE TITLE
There's no reason to seperate the encrypted record layer and the plaintext record layer.

### ISSUE THREAD

**Issue by lukasvrenner** [lukasvrenner/turtls#9]
This separation is bad because it makes its API and the code much more complicated, and it makes handling `ChangeCipherSpec` much more complicated. `ChangeCipherSpec` can be sent when an encrypted message is expected. The AEAD can be stored as an `Option<TlsAead>`, and the record is only decrypted if the message type is application_data and the AEAD is `Some`. Encryption and Decryption can adjust the record type information and move it into the correct place. This way, the higher level doesn't need to determine what is encrypted and what isn't. Once an AEAD is set, everything will be encrypted. This agnosticism will be especially helpful for alerts, where it isn't really relevant to know if it is encrypted or not. When initializing the RecordLayer, the AEAD doesn't need to be zeroed, because it can simply be `None`. Additionally, there need not be a `State` wrapper around the record layer, because it doesn't store anything else. It makes more sense for `Connection` to simply be an `Option<RecordLayer>`.

**Comment by jjohnson-47** [comment]
Anything that would streamline alert handling and avoid unnecessary management makes sense to me!
